### ISSUE TITLE
PortserverFunctionsTest's test_main fails on Debian sid with Python 3.8

### ISSUE THREAD

**Issue by satta** [google/python_portpicker#19]
During Debian packaging, we noticed that the tests recently started to fail on current Debian sid versions:
```
PYTHONPATH=src python3 src/tests/portserver_test.py
I0322 08:56:23.837 139989833676608 portserver.py:191] Port 22 unexpectedly in use, last owning pid 0.
I0322 08:56:23.837 139989833676608 portserver.py:191] Port 22559 unexpectedly in use, last owning pid 0.
I0322 08:56:23.837 139989833676608 portserver.py:195] All ports in use.
..I0322 08:56:23.839 139989833676608 portserver.py:191] Port 12344 unexpectedly in use, last owning pid 0.
I0322 08:56:23.839 139989833676608 portserver.py:187] Can't read start time for pid 12345.
.I0322 08:56:23.839 139989833676608 portserver.py:191] Port 12345 unexpectedly in use, last owning pid 0.
I0322 08:56:23.840 139989833676608 portserver.py:187] Can't read start time for pid 12345.
..W0322 08:56:23.841 139989833676608 portserver.py:247] Could not parse request: invalid literal for int() with base 10: b''
W0322 08:56:23.841 139989833676608 portserver.py:247] Could not parse request: invalid literal for int() with base 10: b'\n'
W0322 08:56:23.841 139989833676608 portserver.py:247] Could not parse request: invalid literal for int() with base 10: b'99Z\n'
W0322 08:56:23.842 139989833676608 portserver.py:247] Could not parse request: invalid literal for int() with base 10: b'99 8\n'
.I0322 08:56:23.843 139989833676608 portserver.py:250] Request on behalf of pid 6.
I0322 08:56:23.843 139989833676608 portserver.py:251] cmdline: <MagicMock name='_get_process_command_line()' id='139989822568720'>
.I0322 08:56:23.845 139989833676608 portserver.py:250] Request on behalf of pid 5.
I0322 08:56:23.845 139989833676608 portserver.py:251] cmdline: <MagicMock name='_get_process_command_line()' id='139989822673872'>
.I0322 08:56:23.847 139989833676608 portserver.py:250] Request on behalf of pid 8.
I0322 08:56:23.847 139989833676608 portserver.py:251] cmdline: <MagicMock name='_get_process_command_line()' id='139989822230384'>
D0322 08:56:23.848 139989833676608 portserver.py:261] Allocated port 999 to pid 8
.......E0322 08:56:23.865 139989833676608 portserver.py:345] No ports.  Invalid port ranges in --portserver_static_pool?
I0322 08:56:23.867 139989833676608 portserver.py:359] Serving on @TST-27521
I0322 08:56:23.868 139989833676608 portserver.py:363] Stopping due to ^C.
I0322 08:56:23.870 139989833676608 portserver.py:267] Dumping statistics:
I0322 08:56:23.870 139989833676608 portserver.py:277] client-request-errors 0
I0322 08:56:23.870 139989833676608 portserver.py:277] denied-allocations 0
I0322 08:56:23.870 139989833676608 portserver.py:277] num-ports-managed 1
I0322 08:56:23.870 139989833676608 portserver.py:277] num-ports-checked-for-last-request 0
I0322 08:56:23.870 139989833676608 portserver.py:277] total-allocations 0
I0322 08:56:23.870 139989833676608 portserver.py:370] Goodbye.
F.E0322 08:56:23.873 139989833676608 portserver.py:312] Ignoring unparsable port range ''.
E0322 08:56:23.873 139989833676608 portserver.py:312] Ignoring unparsable port range 'not'.
E0322 08:56:23.874 139989833676608 portserver.py:312] Ignoring unparsable port range 'numbers'.
E0322 08:56:23.874 139989833676608 portserver.py:312] Ignoring unparsable port range '8080-8081x'.
E0322 08:56:23.874 139989833676608 portserver.py:315] Ignoring out of bounds port range '0-1138'.
E0322 08:56:23.874 139989833676608 portserver.py:315] Ignoring out of bounds port range '1138-65536'.
.I0322 08:56:23.874 139989833676608 portserver.py:111] Not allocating a port to invalid pid
I0322 08:56:23.874 139989833676608 portserver.py:116] Not allocating a port to init.
I0322 08:56:23.877 139989833676608 portserver.py:121] Not allocating a port to a non-existent process
.
======================================================================
FAIL: test_main (__main__.PortserverFunctionsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "src/tests/portserver_test.py", line 154, in test_main
    mock_event_loop.run_until_complete.assert_any_call(
  File "/usr/lib/python3.8/unittest/mock.py", line 984, in assert_any_call
    raise AssertionError(
AssertionError: run_until_complete(<Mock name='start_unix_server()' id='139989822229952'>) call not found

----------------------------------------------------------------------
Ran 19 tests in 0.042s

FAILED (failures=1)
```

**Comment by satta** [comment]
It looks like portserver still works, it's just the test that faisl. We're talking about Python 3.8 here. 
Maybe something changed in `asyncio`?

**Comment by gpshead** [comment]
I dropped test_main and rewrote that test to launch a subprocess instead of using mocks in c33bdd51b8d2e0a24b05a17b8e9b2192f0977dc8 so I doubt this is an issue anymore.
