### ISSUE TITLE
Some tests fail on Windows

### ISSUE THREAD

**Issue by nehaljwani** [google/python_portpicker#4]
```
> python src\tests\portpicker_test.py
sE...s.E.E.
======================================================================
ERROR: testIsPortFree (__main__.PickUnusedPortTest)
This might be flaky unless this test is run with a portserver.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src\tests\portpicker_test.py", line 167, in testIsPortFree
    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY,
AttributeError: 'module' object has no attribute 'IPPROTO_IPV6'

======================================================================
ERROR: testPidDefaultsToOwnPid (__main__.PickUnusedPortTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src\tests\portpicker_test.py", line 91, in testPidDefaultsToOwnPid
    port = portpicker.get_port_from_port_server('portserver')
  File "D:\nwani\m2u\envs\scratch\lib\site-packages\portpicker.py", line 191, in get_port_from_port_server
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: 'module' object has no attribute 'AF_UNIX'

======================================================================
ERROR: testSendsPidToPortServer (__main__.PickUnusedPortTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src\tests\portpicker_test.py", line 82, in testSendsPidToPortServer
    port = portpicker.get_port_from_port_server('portserver', pid=1234)
  File "D:\nwani\m2u\envs\scratch\lib\site-packages\portpicker.py", line 191, in get_port_from_port_server
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: 'module' object has no attribute 'AF_UNIX'

----------------------------------------------------------------------
Ran 11 tests in 1.226s

FAILED (errors=3, skipped=2)
```

**Comment by nehaljwani** [comment]
https://bugs.python.org/issue29515

**Comment by Nidhibar** [comment]
connstring = 'mysql+pymysql://root:password@35.193.120.45/guestbook?/cloudsql/pubsub-quickstart-242108:us-central1-a:myinstance'  
this is the way to connect mysql with cloud sql server
